packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - electron
  - esbuild
  - vue-demi
  - node-gyp
  - unrs-resolver

allowBuilds:
  electron: true
  esbuild: true
  vue-demi: true
  node-gyp: true
